### ISSUE TITLE
dartson and polymer observable

### ISSUE THREAD

**Issue by pjjjv** [eredo/dartson#25]
Dartson works on this example class, but when I add `extends Observable` and `@observable`, it stops working. The object is just null. How to fix this?

Here is the modified example code:
```

@Entity()
class EntityClass extends Observable{
  @observable String name;
  String _setted;

  @Property(name:"renamed")
  bool otherName;

  @Property(ignore:true)
  String notVisible;

  List<EntityClass> children;

  set setted(String s) => _setted = s;
  String get setted => _setted;

  EntityClass();

  factory EntityClass.fromJson(string){
    var dson = new Dartson.JSON();
    EntityClass object = dson.decode(string, new EntityClass());
    return object;
  }
}
```

**Comment by pjjjv** [comment]
My config:

dependencies:
  browser: '>=0.10.0 <0.11.0'
  #firebase: '>=0.5.1 <0.6.0'
  firebase:
    path: ../firebase-dart
  dartson: "^0.2.3"
  paper_elements: '>=0.7.0 <0.8.0'
  polymer: '>=0.16.0 <0.17.0'
transformers:
- polymer:
    entry_points: web/index.html
- dartson

You can find my test project at https://github.com/pjjjv/test_arrays_binding/blob/a96ae100dffb009665f6c17006b0d4156f02bc31/lib/pane_edit.dart

**Comment by eredo** [comment]
After some digging I found a solution which is as simple as switching the order of the transformers array.
Put dartson in front of polymer.

That causes the CodeTransformer for the @observable annotation to be called after dartson has created it's mapping methods which will then use the getter and setter methods created by the Observable CodeTransformer instead of the private properties (__$...) created by the Observable CodeTransformer.

I'm thinking about a proper warning message or detection for these cases.

**Comment by pjjjv** [comment]
Thanks, I'll look into it and try converting my project
