### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by jimirocks** [eredo/dartson#44]
Hello, to me this project seems pretty useful, especially when developing web applications, however, seems in early stage and longer developed.

Can the owner clarify? If it is no longer maintained, what is a show stopper? - if it is the lack of time only I am willing to help. Or are there any technical obstacles?

Thanks

**Comment by eredo** [comment]
Hey, it's the lack of time and there should be a roadmap for future features. Currently it just provides basic JSON to dart mapping functionality. However due to the recent changes in the dart economy (pub transformer to build) this project needs some refactoring before adding new features. 
 Contributions are welcome, but implementation specifics should be discussed in an issue first.

Best regard

**Comment by eredo** [comment]
I'll close this for now and opened #48 to receive further feedback, so I will be able to figure out a proper roadmap to proceed with dartson.
